# Generated by Django 3.2 on 2023-09-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoinment',
            old_name='doctor',
            new_name='Doctor',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
